sudo: required
services:
  - docker

before_install:
  - docker build -t fabiobentoluiz/learn-docker-react -f Dockerfile.dev .

script: 
  - docker run fabiobentoluiz/learn-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: : "eu-central-1"
  app: "learn-docker-react"
  env: "LearnDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-108020393576" 
  bucket_path: "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"